pycodistv1/accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

pycodistv1/blogapp/urls.py
from django.urls import path

from . import views

app_name = "blogapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("articles/", views.showarticles, name="showarticles"),
    path("<int:article_id>/", views.detailarticle, name="detailarticle"),
    path("<int:account_id>/<str:alias>/", views.changealias, name="changealias"),
    path("newarticle/", views.newarticle, name="newarticle"),
]

pycodistv1/pycodistv1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    path('blog/', include('blogapp.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path('', TemplateView.as_view(template_name='index.html'), name='home')
]

pycodistv1/accounts/models.py
from django.db import models

# Create your models here.

pycodistv1/blogapp/models.py
from django.db import models

class Account(models.Model):
    # Full name of the author
    name = models.CharField(max_length=100)
    # Alias/Nickname of the Author, will be seen below the title.
    alias = models.CharField(max_length=50)
    # Total number of article created/published
    num_article = models.IntegerField()

    def __str__(self) -> str:
        return f"Name: {self.name} / Alias: {self.alias}"

    # function to change alias
    def change_alias(self, newalias):
        old_alias = self.alias
        self.alias = newalias
        print(f"New Alias set to : {self.alias} / Old Alias : {old_alias}")
    
    # function to set/increment total articles created/published
    def add_new_article(self):
        self.num_article += 1
        print("A new article from you has been published")

class Article(models.Model):
    # Title of the Article
    title = models.CharField(max_length=100)
    # The owner/publisher of this article
    # author = models.ForeignKey(Account, on_delete=models.CASCADE)
    author = models.IntegerField()
    # The date this Article was created and published
    published_date = models.CharField(max_length=20)

    # def get_author(self):
    #     return f"Author: {self.author}"

    def getinfo(self):
        return [self.title, self.author]

class Comment(models.Model):
    # The article where this comment is placed
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # The account/person who wrote this comment
    alias = models.ForeignKey(Account, on_delete=models.CASCADE)

    def new_comment(self, article_id):
        article = Article.objects.get(pk=article_id)
        print(f"ARTICLE IS : {article}")

pycodistv1/blogapp/forms.py
from django import forms
from django.contrib.auth.models import User

class NewArticle(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    author = forms.IntegerField()

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     print(f"ID : {self.request.user.id}")

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     if self.request and self.request.user.is_authenticated:
    #         user_id = self.request.user.id
    #     self.author = user_id

    #     print(f"AUTHOR : {self.author}")

    #     super(NewArticle, self).__init__(*args, **kwargs)

    
    # def clean(self):
    #     cleaned_data = super(NewArticle, self).clean()
    #     if self.request and self.request.user.is_authenticated:
    #         user_id = self.request.user.id

pycodistv1/accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

pycodistv1/blogapp/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render
from django.http import HttpResponse
from blogapp.models import *
from .forms import NewArticle

def index(request):
    return HttpResponse("HELLO WORLD! FROM BLOG-APP")

# Helper methods
def get_articles():
    articles = Article.objects.all()
    return articles

def showarticles(request):
    articles = Article.objects.all()
    return render(request, "blogapp/index.html", {"article_list": articles})

def detailarticle(request, article_id):
    article = get_object_or_404(Article, pk=article_id)

    print(f"ERROR : {article}")

    info = article.getinfo()
    title = info[0]
    author = get_object_or_404(Account, pk=info[1])
    detail = f"Title: {title} - Author : {author.name}"
    return render(request, "blogapp/detail.html", {"detail": detail})

def changealias(request, account_id, alias):
    author = get_object_or_404(Account, pk=account_id)
    # LOG
    old_alias = author.alias
    author.alias = alias
    author.save()

    return HttpResponse(f"NAME : {author.name}  ALIAS : {author.alias}  / OLD_ALIAS : {old_alias}")

# Handles adding new articles in the database
# TODO: An account dapat is ma automatic na ma kuha ID based ha naka login na account yana
def newarticle(request):
    if request.method == 'POST':
        form = NewArticle(request.POST)
        if form.is_valid():
            print("FORM IS VALID...")
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            try:
                print("USER ID ")
                print(title, content)
                author = Account.objects.get(request.user.id)
                print("================================")            
                
                print(f"TITLE : {title} - CONTENT : {content} - AUTHOR : {author}")
                nArticle = Article()
                nArticle.title = title
                nArticle.content = content
                nArticle.author = author
                nArticle.save()
            except TypeError as e:
                print(e)
            return render(request, 'blogapp/success.html')
    else:
        if request.user.is_authenticated:
            form = NewArticle()
        else:
            form = None
    
    return render(request, 'blogapp/newarticle.html', {'form': form})

pycodistv1/pycodistv1/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect

def index(request):
    return HttpResponse("HELLO WORLD")

pycodistv1/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Django Auth {% endblock %}</title>
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

pycodistv1/templates/blogapp/detail.html
<h3>detail.html</h3>
{% if detail %}
<h1>{{ detail }}</h1>
{% endif %}

pycodistv1/templates/blogapp/index.html
<h3>BlogApp_Index.html</h3>
{% if article_list %}
    <ul>
    {% for article in article_list %}
        <li>{{ article.title }} - {{ article.author }}</li>
        <br>
    {% endfor %}
    </ul>
    {% else %}
    <p>No articles are available.</p>
{% endif %}

pycodistv1/templates/blogapp/newarticle.html
<!DOCTYPE html>
<head>
  <title>My Page Title</title>
  <meta http-equiv="Content-Type" content="text/html"; charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>

  <style>
  </style>

</head>

<h1>NEWARTICLE.html</h1>

{% block content %}
{% if user.is_authenticated %}
<form method="post" action="{% url 'blogapp:newarticle' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% else %}
<h1>NOT LOGIN</h1>
{% endif %}
{% endblock %}

pycodistv1/templates/blogapp/success.html
<h1>DONE!</h1>

pycodistv1/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>User Profile</title>
    <meta http-equiv="Content-Type" content="text/html" ; charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    <style>
        body {
            background-color: #f4f4f4;
            padding-top: 20px;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            border-radius: 4px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        .container2 {
            max-width: 400px;
            margin: 0 auto;
            padding: 40px;
            margin-top: 100px;
            background-color: #fff;
            border-radius: 4px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .avatar {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background-color: #ccc;
        }

        .user-info {
            display: flex;
            align-items: center;
        }

        .user-info h4 {
            margin-left: 10px;
        }

        .logout-button {
            background-color: #e74c3c;
            color: #fff;
            border: none;
            padding: 8px 12px;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
            /* added to remove underline */
        }

        .content {
            line-height: 1.6;
        }

        .login-button {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            padding: 8px 12px;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
        }

        .login-button:hover {
            background-color: #45a049;
        }

        .container3 {
            max-width: 400px;
            margin: 0 auto;
            text-align: center;
            padding: 40px;
            margin-top: 100px;
            background-color: #fff;
            border-radius: 4px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .header2 {
            margin-bottom: 30px;
        }
    </style>
</head>

<body>

    {% block content %}
    {% if user.is_authenticated %}
    <!-- <h4>Hello {{ user.username }}</h4> -->
    <div class="container">
        <div class="header">
            <div class="user-info">
                <div class="avatar"></div>
                <h4>Username : {{ user.username }}</h4>
                <h4>ID : {{ user.id }}</h4>
            </div>
            <a href="{% url 'logout' %}" class="logout-button">Logout</a>

        </div>

        <div class="content">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur euismod sagittis.
                Proin vulputate urna vel elit semper, sed tempor elit convallis. Mauris mattis, felis vel
                gravida gravida, sem felis varius arcu, sed suscipit nulla neque ac libero.
            </p>
            <p>
                Pellentesque eu dui ut enim pretium euismod ut et lectus. Integer dapibus sem non enim
                volutpat, eu consectetur lorem lacinia. Aenean tristique erat dolor, sed sollicitudin
                magna gravida nec. Ut euismod nisi et tortor fermentum, a feugiat odio maximus.
            </p>
            <p>
                Aliquam sit amet iaculis lacus. Nunc bibendum ex vel eleifend elementum. Vivamus
                tincidunt lectus in cursus efficitur. Duis vehicula auctor arcu, non lobortis sem
                tristique ut.
            </p>
        </div>
    </div>

    {% else %}
    <div class="container3">
        <h2 class="header2">You are not logged in.</h2>
        <a href="{% url 'login' %}" class="login-button">Login</a>
        <a href="{% url 'signup' %}" class="login-button">Signup</a>
    </div>
    {% endif %}
    {% endblock %}
</body>

</html>